### PR TITLE
WIP: streaming image to histogram filter

### PR DESCRIPTION
**Pull request by romangrothausmann**
In regard to #2 this PR tries to implement a `StreamingImageToHistogramFilter`

### CODE REVIEW

**Comment by romangrothausmann** [comment]
@blowekamp Is it OK to replace `ImageTransformer` with `ImageSinc` (https://github.com/blowekamp/itkStreamingSinc/pull/3/commits/5daf1620a5f28da70efb1676e97844e53cb46552)?
 I am stuck on the changes corresponding to https://github.com/blowekamp/itkStreamingSinc/commit/b4ae9b61dc08388fbf1b3bfd9e5cf570dd40a0c6. How would you cope with those for `StreamingImageToHistogramFilter`? I guess we'd need adjustments at least here: https://github.com/blowekamp/itkStreamingSinc/blob/0dfa01f458d6a19496a5d3c99333d47466e2f70b/include/itkStreamingImageToHistogramFilter.hxx#L222-L227.

**Comment by blowekamp** [comment]
This is GREAT!

It has been a while since I have looked at this code. 

Yes I think the ImageSinc class is the right parent. I assume you are familiar with the usual `BeforeThreadedGenerateData`, `ThreadedGenerateData` and `AfterThreadedGenerateData`. This class hierarchy introduces, `BeforeStreamedGenerateData`, `ThreadedStreamedGenerateData` and `AfterStreamedGenerateData`.  Where `ThreadedStreamedGenerateData` will be called concurrently for multiple threads, and multiple time for different streamed regions.

For this filter the histogram is the output. In the end every things gets reduced to one histogram. The one difficulty with this is that the parameters for all the histograms need to be the same. That is we need to know the min and max, which requires all the data. So either this input needs to be streamed multiple times, or the whole volume is needed or the min/max needs to be know a priori.

In `BeforeStreamedGenerateData` all the per thread histograms should be sized properly and initialized to 0. Then in `ThreadedStreamedGenerateData` the the operation needs to be changed from zeroing and setting, to accumulated the histogram for each streamed chunk. Lastly, the `AfterStreamedGenerateData` step should remain the same of accumulating the all the threads.

ALTERNATIVELY. 
This process has changed in ITKv5, there are no longer per-thread histograms. There is just a histogram local to the thread in the `ThreadedGeneteraData` method, which gets merged in [`ThreadedMergeHistogram` ](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx#L269). Not sure which is easy to update this code too.

**Comment by romangrothausmann** [comment]
Many thanks @blowekamp  for your detailed reply. I'm only partially "familiar with the usual BeforeThreadedGenerateData, ThreadedGenerateData and AfterThreadedGenerateData" but I guess I do get what you suggest ought to be done and I would give it a try next week.
However, if you feel an urge to continue the implementation please go ahead;-) `Allow edits from maintainers` is on. ITK-5 would be fine for me. 

Does itkStreamingSinc already work with current ITK-5? 
Even with `-DModule_StreamingSinc=ON` (https://github.com/romangrothausmann/ITK-CLIs/blob/a926cdcdb1e64cf9020de685be02b64e64b261e0/Dockerfile#L38)
using StreamingSinc does not work, see e.g. this log:
https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/172811755
reporting:
```
In file included from /opt/itk/include/ITK-5.0/itkImageSinc.h:123:0,
                 from /opt/itk/include/ITK-5.0/itkStreamingStatisticsImageFilter.h:21,
                 from /code/stat.cxx:13:
/opt/itk/include/ITK-5.0/itkImageSinc.hxx: In static member function 'static void* itk::ImageSinc<TInputImage>::ThreaderCallback(void*)':
/opt/itk/include/ITK-5.0/itkImageSinc.hxx:176:36: error: 'MultiThreader' has not been declared
```

**Comment by romangrothausmann** [comment]
@blowekamp  Currently I am wondering why the `ImageToHistogramFilter` is not already streaming by default. 
Streaming for the `StatisticsImageFilter` is not implemented because of its possible use in the middle of a pipeline using `StatisticsImageFilter` (unmodified) output to re-update the pipeline. However `ImageToHistogramFilter` has the histogram as output, which would not be driven by any successive image streaming. 
So perhaps this contribution here should go directly into `ImageToHistogramFilter` in https://github.com/InsightSoftwareConsortium/ITK?

**Comment by blowekamp** [comment]
Yes it would have been nice to get this into ITK when it was up today. Not it does require a bit of effort to update it to ITKv5, and improve the system to support the features here. It would be nice to do, but I don't have time for it in the near future.

**Comment by blowekamp** [comment]
@romangrothausmann Thank you for the nudge. I'm now pursuing adding these classes into upstream ITK in time for the ITKv5 release.

**Comment by romangrothausmann** [comment]
@blowekamp That's fantastic! I'm very much looking forward to that and think that it will be a very valuable contribution. I'm happy to help with testing (but fear I'm currently not able to offer more).

**Comment by blowekamp** [comment]
Testing is very much needed at this late point in time in the ITKv5 development. So your contribution is very valuable!

**Comment by romangrothausmann** [comment]
Many thanks @blowekamp for getting into this.
Just as a reference, this suggested changes of this PR are realized in:
https://github.com/InsightSoftwareConsortium/ITK/pull/855/commits/6287992f244ae5609454676b65f864997d15c552

**Comment by romangrothausmann** [comment]
Now in ITK, many thanks @blowekamp.

**Pull request closed without merging**
